name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    name: Check commits messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v5
